name: CI Test

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - run: npm run lint
      - run: npm run cov
      - uses: codecov/codecov-action@v1
